config-version: '1.0'
checks:
  player:
    enabled: true
    max-occluding-count: 3
    always-show-radius: 16
    raycast-radius: 48
    visible-recheck-interval: 50
    only-cull-while-sneaking: true
  entity:
    enabled: true
    max-occluding-count: 1
    always-show-radius: 1
    raycast-radius: 48
    visible-recheck-interval: 10
  tile-entity:
    enabled: true
    max-occluding-count: 3
    always-show-radius: 1
    raycast-radius: 48
    visible-recheck-interval: 10
    exempted-blocks:
    - BEACON
snapshot:
  block:
    mode: unsafe-async-bukkit, sync-bukkit, packetevents
    sync-bukkit:
      refresh-interval: 60
    unsafe-async-bukkit:
      refresh-interval: 60
    packetevents:
      #Leave blank but add ability to add options here
  entity:
    mode: bukkit, packetevents
    bukkit:
      #Leave blank but add ability to add options here
    packetevents:
      #Leave blank but add ability to add options here
  tile-entity:
    mode: bukkit, packetevents
    bukkit:
      #Leave blank but add ability to add options here
    packetevents:
      #Leave blank but add ability to add options here
visibility-handlers:
  block:
    mode: bukkit, packetevents
    bukkit:
      #Leave blank but add ability to add options here
    packetevents:
      #Leave blank but add ability to add options here
  entity:
    mode: bukkit, packetevents
    bukkit:
      #Leave blank but add ability to add options here
    packetevents:
      #Leave blank but add ability to add options here
  tile-entity:
    mode: bukkit, packetevents
    bukkit:
      #Leave blank but add ability to add options here
    packetevents:
      #Leave blank but add ability to add options here
debug:
  info-level: 5
  warn-level: 5
  error-level: 5
  particles: false
  timings: false
  log-to-file: false
engine:
  mode: simple, predictive
  simple:
    #Leave blank but add ability to add options here
  predictive:
    leniency: 30
